In [1]:
import numpy as np

In [16]:
matrix = np.loadtxt('/home/pclarke/Teaching/NumericalRecipes/Unit1-Matrices/java/SimultaneousMatrix.txt')
vector = np.loadtxt('/home/pclarke/Teaching/NumericalRecipes/Unit1-Matrices/java/SimultaneousVector.txt')

In [17]:
matrix, vector

(array([[  3.,   4.,   8.,   5.,   4.],
        [  5.,   6.,   9.,  10.,   1.],
        [  7.,   3.,   9.,   3.,   2.],
        [ 12.,  15.,  20.,   5.,   9.],
        [  9.,   3.,   5.,   6.,   8.]]),
 array([ 170.,  204.,  138.,  394.,  223.]))

In [19]:
np.matmul( np.linalg.inv(matrix), matrix)

array([[  1.00000000e+00,  -1.11022302e-16,  -1.11022302e-16,
          2.22044605e-16,  -1.11022302e-16],
       [ -3.60822483e-16,   1.00000000e+00,  -5.20417043e-17,
         -1.90819582e-17,   4.85722573e-17],
       [  2.22044605e-16,   1.11022302e-16,   1.00000000e+00,
         -1.11022302e-16,   0.00000000e+00],
       [ -5.55111512e-17,  -1.38777878e-16,  -2.77555756e-17,
          1.00000000e+00,  -5.55111512e-17],
       [ -1.11022302e-16,   2.22044605e-16,   2.77555756e-16,
         -1.11022302e-16,   1.00000000e+00]])

In [20]:
np.matmul( np.linalg.inv(matrix), vector)

array([  3.,   7.,   5.,   9.,  12.])

In [21]:
3*3+7*4+8*5+9*5+12*4

170

In [23]:
coeffs = np.loadtxt('/home/pclarke/Teaching/NumericalRecipes/Unit1-Matrices/java/SimultaneousMatrix.txt')
vector = np.loadtxt('/home/pclarke/Teaching/NumericalRecipes/Unit1-Matrices/java/SimultaneousVector.txt')

In [24]:
mcoeffs = np.matrix(coeffs)
mvector = np.matrix(vector)

In [25]:
mcoeffs.I

matrix([[-0.23276134,  0.03610906,  0.10253711,  0.01273818,  0.07190231],
        [-0.19128329,  0.09322034, -0.18280872,  0.11743341, -0.00242131],
        [ 0.19012528, -0.06816507,  0.12859248, -0.03279293, -0.08179808],
        [ 0.0416886 ,  0.09801032, -0.0482156 , -0.04705759,  0.03189809],
        [ 0.183493  , -0.10648489, -0.09100958, -0.00257922,  0.07221813]])

In [26]:
mcoeffs.I*mcoeffs

matrix([[  1.00000000e+00,  -1.11022302e-16,  -1.11022302e-16,
           2.22044605e-16,  -1.11022302e-16],
        [ -3.60822483e-16,   1.00000000e+00,  -5.20417043e-17,
          -1.90819582e-17,   4.85722573e-17],
        [  2.22044605e-16,   1.11022302e-16,   1.00000000e+00,
          -1.11022302e-16,   0.00000000e+00],
        [ -5.55111512e-17,  -1.38777878e-16,  -2.77555756e-17,
           1.00000000e+00,  -5.55111512e-17],
        [ -1.11022302e-16,   2.22044605e-16,   2.77555756e-16,
          -1.11022302e-16,   1.00000000e+00]])

In [28]:
mcoeffs.I*mvector.T

matrix([[  3.],
        [  7.],
        [  5.],
        [  9.],
        [ 12.]])